#!/bin/bash
# =============================================================================
# Script 5: Open Source Manifesto Generator
# Course  : Open Source Software (OSS NGMC)
# Purpose : Interactively ask the user three questions, then compose a
#           personalised open-source philosophy statement and save it to a
#           .txt file named after the current user.
# Concepts: read for user input, string concatenation, writing to a file
#           with > and >>, date command, aliases demonstrated via comments.
# =============================================================================

# --- Alias concept demonstration (comment) ---
# In a live shell session you could define:
#   alias mkmanifesto='bash script5_manifesto_generator.sh'
# Then run it simply as: mkmanifesto
# Aliases make frequently used commands shorter and more memorable.
# They are personal shortcuts — much like open-source forks:
# taking something that exists and reshaping it for your own needs.

echo "========================================================"
echo "    Open Source Manifesto Generator — OSS Audit Tool   "
echo "========================================================"
echo ""
echo "  Answer three questions to generate your personal"
echo "  open-source philosophy statement."
echo ""

# --- Gather user input interactively ---
# read -p prints a prompt then waits for input; result stored in variable

read -p "  1. Name one open-source tool you use every day: " TOOL
echo ""

read -p "  2. In one word, what does 'freedom' mean to you? " FREEDOM
echo ""

read -p "  3. Name one thing you would build and share freely: " BUILD
echo ""

# --- Capture current date and username for the document ---
DATE=$(date '+%d %B %Y')        # e.g. "22 March 2026"
AUTHOR=$(whoami)                 # Current logged-in username

# --- Output file: named after the user for easy identification ---
OUTPUT="manifesto_${AUTHOR}.txt"

# --- Compose the manifesto paragraph using string concatenation ---
# Each echo >> appends a new line to the output file.
# The first > creates (or overwrites) the file; >> appends after that.

# Create/overwrite the file with the header
echo "========================================================" > "$OUTPUT"
echo "           MY OPEN SOURCE MANIFESTO                    " >> "$OUTPUT"
echo "========================================================" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "  Author : $AUTHOR" >> "$OUTPUT"
echo "  Date   : $DATE" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "--------------------------------------------------------" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# --- The personalised manifesto paragraph ---
# Variables are interpolated inside double-quoted strings.
# String concatenation in bash is simply placing variables next to text.

echo "  Every day I use $TOOL — a piece of software built by" >> "$OUTPUT"
echo "  people who chose to share their work rather than lock" >> "$OUTPUT"
echo "  it away. That choice changed what is possible for me." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "  To me, freedom means $FREEDOM. In the world of software," >> "$OUTPUT"
echo "  that freedom is not abstract. It lives in source code" >> "$OUTPUT"
echo "  anyone can read, in licenses that protect the right to" >> "$OUTPUT"
echo "  learn, modify, and redistribute." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "  I believe in giving back. If I could build one thing" >> "$OUTPUT"
echo "  and share it freely with the world, it would be" >> "$OUTPUT"
echo "  $BUILD — because knowledge hoarded is knowledge wasted," >> "$OUTPUT"
echo "  but knowledge shared is knowledge multiplied." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "  I stand on the shoulders of giants. Every compiler," >> "$OUTPUT"
echo "  every kernel, every library beneath my work was a gift." >> "$OUTPUT"
echo "  This manifesto is my commitment to keep that gift moving." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "--------------------------------------------------------" >> "$OUTPUT"
echo "  Generated by: script5_manifesto_generator.sh" >> "$OUTPUT"
echo "  OSS Audit Capstone | Open Source Software Course" >> "$OUTPUT"
echo "========================================================" >> "$OUTPUT"

# --- Confirm and display the result ---
echo "  -------------------------------------------------------"
echo "  Manifesto saved to: $OUTPUT"
echo "  -------------------------------------------------------"
echo ""

# cat: display the file contents to the terminal
cat "$OUTPUT"
